spring:
  application:
    name: donaton-ms-logistica

  datasource:

    url: jdbc:postgresql://localhost:5432/bd_logistica
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8082